package com.view;

// Generated 23 Nov, 2016 5:43:11 PM by Hibernate Tools 3.4.0.CR1

/**
 * College generated by hbm2java
 */
public class College implements java.io.Serializable {

	private Integer clgId;
	private Depa depa;
	private String name;
	private String email;

	public College() {
	}

	public College(Depa depa, String name, String email) {
		this.depa = depa;
		this.name = name;
		this.email = email;
	}

	public Integer getClgId() {
		return this.clgId;
	}

	public void setClgId(Integer clgId) {
		this.clgId = clgId;
	}

	public Depa getDepa() {
		return this.depa;
	}

	public void setDepa(Depa depa) {
		this.depa = depa;
	}

	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	public String getEmail() {
		return this.email;
	}

	public void setEmail(String email) {
		this.email = email;
	}

}
