package com.view;

// Generated 23 Nov, 2016 2:54:38 PM by Hibernate Tools 3.4.0.CR1

/**
 * Emp generated by hbm2java
 */
public class Emp implements java.io.Serializable {

	private Integer empId;
	private Dept dept;
	private String empName;
	private String empSalary;

	public Emp() {
	}

	public Emp(Dept dept, String empName, String empSalary) {
		this.dept = dept;
		this.empName = empName;
		this.empSalary = empSalary;
	}

	public Integer getEmpId() {
		return this.empId;
	}

	public void setEmpId(Integer empId) {
		this.empId = empId;
	}

	public Dept getDept() {
		return this.dept;
	}

	public void setDept(Dept dept) {
		this.dept = dept;
	}

	public String getEmpName() {
		return this.empName;
	}

	public void setEmpName(String empName) {
		this.empName = empName;
	}

	public String getEmpSalary() {
		return this.empSalary;
	}

	public void setEmpSalary(String empSalary) {
		this.empSalary = empSalary;
	}

}
