package com.view;

// Generated Dec 21, 2016 1:23:54 PM by Hibernate Tools 3.4.0.CR1

import java.math.BigDecimal;
import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Employee generated by hbm2java
 */
public class Employee implements java.io.Serializable {

	private Long employeeId;
	private String name;
	private String address;
	private String gender;
	private Double salary;
	private Date birthDate;
	private Set skills = new HashSet(0);

	public Employee() {
	}

	public Employee(String name, String address, Double salary,
			Date birthDate) {
		this.name = name;
		this.address = address;
		this.salary = salary;
		this.birthDate = birthDate;
	}

	public Employee(String name, String address, String gender,
			Double salary, Date birthDate, Set skills) {
		this.name = name;
		this.address = address;
		this.gender = gender;
		this.salary = salary;
		this.birthDate = birthDate;
		this.skills = skills;
	}

	public Long getEmployeeId() {
		return this.employeeId;
	}

	public void setEmployeeId(Long employeeId) {
		this.employeeId = employeeId;
	}

	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	public String getAddress() {
		return this.address;
	}

	public void setAddress(String address) {
		this.address = address;
	}

	public String getGender() {
		return this.gender;
	}

	public void setGender(String gender) {
		this.gender = gender;
	}

	public Double getSalary() {
		return this.salary;
	}

	public void setSalary(Double salary2) {
		this.salary = salary2;
	}

	public Date getBirthDate() {
		return this.birthDate;
	}

	public void setBirthDate(Date birthDate) {
		this.birthDate = birthDate;
	}

	public Set getSkills() {
		return this.skills;
	}

	public void setSkills(Set skills) {
		this.skills = skills;
	}

}
