package com.view;

// Generated Dec 21, 2016 1:23:54 PM by Hibernate Tools 3.4.0.CR1

/**
 * SkillmasterId generated by hbm2java
 */
public class SkillmasterId implements java.io.Serializable {

	private short skillId;
	private String skillName;

	public SkillmasterId() {
	}

	public SkillmasterId(short skillId, String skillName) {
		this.skillId = skillId;
		this.skillName = skillName;
	}

	public short getSkillId() {
		return this.skillId;
	}

	public void setSkillId(short skillId) {
		this.skillId = skillId;
	}

	public String getSkillName() {
		return this.skillName;
	}

	public void setSkillName(String skillName) {
		this.skillName = skillName;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof SkillmasterId))
			return false;
		SkillmasterId castOther = (SkillmasterId) other;

		return (this.getSkillId() == castOther.getSkillId())
				&& ((this.getSkillName() == castOther.getSkillName()) || (this
						.getSkillName() != null
						&& castOther.getSkillName() != null && this
						.getSkillName().equals(castOther.getSkillName())));
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + this.getSkillId();
		result = 37 * result
				+ (getSkillName() == null ? 0 : this.getSkillName().hashCode());
		return result;
	}

}
