package com.view;

// Generated Dec 21, 2016 1:23:54 PM by Hibernate Tools 3.4.0.CR1

/**
 * Skill generated by hbm2java
 */
public class Skill implements java.io.Serializable {

	private short skillId;
	private Employee employee;

	public Skill() {
	}

	public Skill(short skillId) {
		this.skillId = skillId;
	}

	public Skill(short skillId, Employee employee) {
		this.skillId = skillId;
		this.employee = employee;
	}

	public short getSkillId() {
		return this.skillId;
	}

	public void setSkillId(short skillId) {
		this.skillId = skillId;
	}

	public Employee getEmployee() {
		return this.employee;
	}

	public void setEmployee(Employee employee) {
		this.employee = employee;
	}

}
