package com.view;

// Generated Dec 21, 2016 1:23:54 PM by Hibernate Tools 3.4.0.CR1

/**
 * Skillmaster generated by hbm2java
 */
public class Skillmaster implements java.io.Serializable {

	private SkillmasterId id;

	public Skillmaster() {
	}

	public Skillmaster(SkillmasterId id) {
		this.id = id;
	}

	public SkillmasterId getId() {
		return this.id;
	}

	public void setId(SkillmasterId id) {
		this.id = id;
	}

}
