package com.view;

// Generated Dec 22, 2016 2:38:01 PM by Hibernate Tools 3.4.0.CR1

/**
 * Employee generated by hbm2java
 */
public class Employee implements java.io.Serializable {

	private Integer empId;
	private Department department;
	private String empName;
	private String empPhoneNo;
	private String empEmail;

	public Employee() {
	}

	public Employee(Department department, String empName, String empPhoneNo,
			String empEmail) {
		this.department = department;
		this.empName = empName;
		this.empPhoneNo = empPhoneNo;
		this.empEmail = empEmail;
	}

	public Integer getEmpId() {
		return this.empId;
	}

	public void setEmpId(Integer empId) {
		this.empId = empId;
	}

	public Department getDepartment() {
		return this.department;
	}

	public void setDepartment(Department department) {
		this.department = department;
	}

	public String getEmpName() {
		return this.empName;
	}

	public void setEmpName(String empName) {
		this.empName = empName;
	}

	public String getEmpPhoneNo() {
		return this.empPhoneNo;
	}

	public void setEmpPhoneNo(String empPhoneNo) {
		this.empPhoneNo = empPhoneNo;
	}

	public String getEmpEmail() {
		return this.empEmail;
	}

	public void setEmpEmail(String empEmail) {
		this.empEmail = empEmail;
	}

}
