// default package
// Generated Dec 12, 2016 2:08:48 PM by Hibernate Tools 3.4.0.CR1

import java.util.HashSet;
import java.util.Set;

/**
 * Teacher generated by hbm2java
 */
public class Teacher implements java.io.Serializable {

	private Integer teacherId;
	private String teacherName;
	private String teachCode;
	private Set students = new HashSet(0);

	public Teacher() {
	}

	public Teacher(String teacherName, String teachCode, Set students) {
		this.teacherName = teacherName;
		this.teachCode = teachCode;
		this.students = students;
	}

	public Integer getTeacherId() {
		return this.teacherId;
	}

	public void setTeacherId(Integer teacherId) {
		this.teacherId = teacherId;
	}

	public String getTeacherName() {
		return this.teacherName;
	}

	public void setTeacherName(String teacherName) {
		this.teacherName = teacherName;
	}

	public String getTeachCode() {
		return this.teachCode;
	}

	public void setTeachCode(String teachCode) {
		this.teachCode = teachCode;
	}

	public Set getStudents() {
		return this.students;
	}

	public void setStudents(Set students) {
		this.students = students;
	}

}
